### ISSUE TITLE
Done button only worked once

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#120]
In the only model I've done so far, Overtake1, I clicked Done, got the warning that I needed to set a root node, closed the warning with "Don't exit", set the variable Delay as root (which should have been a parameter but wasn't due to bug reported earlier), then clicked Done again.  Nothing happened

**Comment by sachingrover211** [comment]
Professor @vanlehn , I have not been able to reproduce this bug. I have tried a lot of combination of windows and chrome as well. Even on the laptops or desktops where the radio button issue exists even there this bug is not reproducible.

**Comment by sachingrover211** [comment]
May be I am missing something in the steps. Would it be possible to show us this bug again, or something of the sorts so that we can understand what is wrong?

**Comment by jonwetzel** [comment]
Kurt can't reproduce this either, so we'll close it for now.
