### ISSUE TITLE
To pair quantity nodes with descriptions, use interior color instead of border color

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#121]
I've only got a few nodes, and already I can't tell the colors apart on the borders.  Let's use fewer colors, but also use dotted and dashed borders beside the solid ones.  This means that we can't used dotted borders for indicating incomplete nodes.  However, we now have the ability to use icons on student nodes in order to indicate their correctness.  Let's also use an icon (I suggest a ? inside a circle) to indicate that a node is incomplete.

**Comment by sachingrover211** [comment]
@jonwetzel we need to decide how to make the changes. One idea that I had was change the colors to particularly distinct 10 to 15 colors rather than 40 and then try it for sometime.

**Comment by vanlehn** [comment]
Instead of using the color of the interior of a node to pair up only equations with their explanations, lets also color the interiors of quantity nodes to pair them with their descriptions.  The borders of all nodes can be black, and a dotted border can still mean that the node is incomplete.  Second, we should change the shape of the quantity descriptions, which are now rectangles, so that they have rounded ends and thus have the same shape as the quantity nodes.  That will make it easier for students to remember how the pairings work.

**Comment by jonwetzel** [comment]
https://github.com/Dragoon-Lab/topomath/pull/130
