### ISSUE TITLE
Implement remaining topomath models from Spring semester.

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#136]
Consider making a script that reads models and creates a test case for them.

**Comment by jonwetzel** [comment]
@vanlehn Please attach link to google doc here.

**Comment by vanlehn** [comment]
The Q-matrix lists problems vertically in  the order they were assigned.
https://docs.google.com/spreadsheets/d/1CuKFUr95Gs5BPJo8N4A9L7otvFITI4yKWbvVaQedrU0/edit#gid=0

**Comment by vanlehn** [comment]
better card
