### ISSUE TITLE
convert spring 17 problems to topomath

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#150]
See Qmatrix
https://docs.google.com/spreadsheets/d/1CuKFUr95Gs5BPJo8N4A9L7otvFITI4yKWbvVaQedrU0/edit 
Create a user named Pilot.
Put all the models in one folder named Spring2017
Share the folder with kvl

**Comment by vanlehn** [comment]
https://drive.google.com/drive/folders/0B50YudTp0iGbZGxLdmVvQ0xFY00

**Comment by jonwetzel** [comment]
@vanlehn I created a user account "dragoonlabauthor" and created the first model (https://docs.google.com/spreadsheets/d/1c6A6XHisbBg4EX139KKplGqZiZcYRDaWP5MNhTWOfo8/edit#gid=123560873) and a system description for it.  

You should be able to:

1. Log into http://topomath.asu.edu/devel-lms as user kvl
1. Click on "Models" and then find folder "Spring2017" shared with you.
1. Click on the DRT - 1 model inside that folder and open and edit it in author mode
1. Click on the DRT - 1 model inside that folder and view or edit the system description I made.

**Comment by jonwetzel** [comment]
Two design decisions needed to be made first: 

1. Do we give equations or not?
2. Do we include variable names in the descriptions or not?

After looking at some more examples, I think we should just give English explanations which state the relationship between the variables in English, but not give the whole equation.  This includes naming the variables by name so the student has some idea of what variables to use.  Not all variables need be included (see [DRT_and_change_Tom March 24](https://docs.google.com/spreadsheets/d/1Wpe2ShuPVsUSlpYMJdWZOs-KOJ5HB6Xfao-lrY9uBPM/edit#gid=0))

**Comment by jonwetzel** [comment]
@vanlehn Some of these have multiple examples (in different sheets).  Should I start by making one for each spreadsheet or one for each sheet?  (Some of the individual sheets seem incomplete, others redundant--if we need a model for every sheet I'll assume I can skip these...)

**Comment by jonwetzel** [comment]
@vanlehn I've updated the first model and implemented two more models using the new convention described two comments up.  Please take a look.

**Comment by vanlehn** [comment]
@jonwetzel I added my responses to your comments.  Looking good!

**Comment by jonwetzel** [comment]
@vanlehn  Great, thanks!  I'll do one model per google sheet then.

**Comment by jonwetzel** [comment]
@vanlehn There should now be one model for each sheet except the one we discussed and decided to skip in the doc comments earlier.  I gave each model one system description.  I arranged the nodes in a somewhat consistent pattern with quantities for the left hand and right hand sides of equations placed on opposite sides of their respective equation nodes.  For many schemas I added variable names to the explanations, but in some cases variable names wouldn't fit grammatically and the meaning was pretty clear from the sentence anyway.  Hopefully students can understand those.

Also, please note which model you are on if the links don't appear between the nodes when you first load a problem.  I saw that happen twice, but am not sure how to reproduce it... (clicking "check equation" on each equation seems to fix it).
