### ISSUE TITLE
Add System description link on page in Student Mode

### ISSUE THREAD

**Issue by dharanisakary** [Dragoon-Lab/topomath#168]

**Comment by riteshsamala** [comment]
Hey @dharanisakary , can you divide this into two tasks. Sending out link for each problem on LMS is something we need to figure out how to do and size estimate will be more.

**Comment by dharanisakary** [comment]
As discussed with Professor, we decided to provide link to system description explicitly for now.

**Comment by riteshsamala** [comment]
yeah that was one option, also in the discussion prof talked about any quick hack. In discussion we further thought to give it a couple of days and see. If that works we ll separate the tasks else go with current state like discussed

**Comment by jonwetzel** [comment]
We will use another workaround for this.
