### ISSUE TITLE
Auto-created quantity nodes are stuck on "Unknown"

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#172]
1. Create an equation "O = DC + D"
1. Open node O and give it a description.  Leave it as unknown.
1. Open node DC and give it a description.  Try changing it to parameter.

Clicking on "Parameter" radio button and text does nothing.  Same happens for node D and O.

**Comment by jonwetzel** [comment]
Assigning to @dharanisakary.  Please aim to fix this by next Wednesday.  Workaround is to close the model and open it again.

**Comment by dharanisakary** [comment]
Hey Jon - I faced this issue while writing test cases. I fixed this issue and committed to the build_features branch. Is it the same branch you are working on? And regarding value, I will clear the value on changing variable type.

**Comment by jonwetzel** [comment]
@dharanisakary  I've pulled the new master to devel on the server and that seems to have fixed it.  Thanks much.

**Comment by dharanisakary** [comment]
Thanks Jon!
