### ISSUE TITLE
Student mode: Type selection should turn green/red/yellow

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#203]
Add some highlighting behind that selected radio button text (and button itself, if possible) to indicate if it was incorrect, correct or demo.

- [ ] Create a mockup or two using javascript/html in the real node editor and attach screenshots to this card.
- [ ] After approval, write code to implement it.  (First talk with @sachingrover211 who is refactoring student mode node editor)

**Comment by dharanisakary** [comment]
![feedbackicons1](https://user-images.githubusercontent.com/17277920/34131380-3323e604-e400-11e7-8096-ec315625e14c.png)

**Comment by jonwetzel** [comment]
Design approved.  Work with @sachingrover211 as he is also working on these radio buttons for issue #260 .
