### ISSUE TITLE
Prepare Dragoon problems for CPI 360

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#216]
Attached is a word file with the 3 problems sets that I would like to assign.  This task has 3parts.  

First, generate a problem link to replace the ones in this file using the new class instead of the old one.  The model is usually immediate feedback on entries and graphs.  The ones that marked TNS required are to be done with feedback on everytyhing.  The ones marked TEST are to be done with feedback on graph only.  Give me back a word file with the revised links.

Second, remove public access to the mastery model construction.

third, check the links in problem set to make sure that all the problems can be solved without problems.  This can be a spot check, if things seem to be working ok.

**Comment by jonwetzel** [comment]
@riteshsamala As you set up the new site, please do part 2 above.  After the site is live and finished, do part 1 and part 3.

**Comment by riteshsamala** [comment]
@jonwetzel can you please attach the word file with the problem sets prof is referring to. I do not see any attachments here.

Thanks-
Ritesh
