### ISSUE TITLE
Refactor feedback for node editing

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#222]
The architecture for giving feedback to students is messy leading to various bugs with the radio buttons.  It needs a complete refactor.  

TODO: Find node editor control/feedback bugs and list them here, then close their issues as duplicates.

Will fix: 

- https://github.com/Dragoon-Lab/topomath/issues/184
- https://github.com/Dragoon-Lab/topomath/issues/201
- https://github.com/Dragoon-Lab/topomath/issues/191

Also:

- [ ] Re-enable "dynamic" checkbox

**Comment by jonwetzel** [comment]
Fixes #184 and #191

**Comment by sachingrover211** [comment]
This has been split up into four different cards
#260 #261 #262 #263
