### ISSUE TITLE
Use AJAXification in Drupal forms and add error handling

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#231]

**Comment by riteshsamala** [comment]
Ajaxification
- [ ] Create Folder Form 
- [ ] Create Model Form
- [ ] Rename Items Form
- [ ] Move/Copy items Form
- [ ] Delete Items Form
- [ ] Sharing Form
- [ ] Open Model Form
- [ ] Save assignment Form
- [ ] System Descriptions Upload Form

**Comment by riteshsamala** [comment]
Error Handling API side
- [x] Create Folder Form 
- [x] Create Model Form
- [x] Rename Items Form
- [ ] Move/Copy items Form
- [ ] Delete Items Form
- [ ] Sharing Form
- [ ] Open Model Form
- [ ] Save assignment Form
- [ ] System Descriptions Upload Form
