### ISSUE TITLE
Student Mode Node Editor Radio Button Handler

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#260]

**Comment by jonwetzel** [comment]
@sachingrover211, consider incorporating  https://github.com/Dragoon-Lab/topomath/issues/203 by @dharanisakary into this branch too.

**Comment by sachingrover211** [comment]
@jonwetzel Currently working on this.

**Comment by jonwetzel** [comment]
Done in https://github.com/Dragoon-Lab/topomath/pull/295
