### ISSUE TITLE
Students can receive yellow value on a field which doesn't exist for that node.

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#282]
1. Open a model which contains an unknown quantity in student mode.
1. Click add quantity and choose the description and name for the unknown quantity.
1. Select parameter or dynamic as the type.
1. Enter numbers into the value field until you get a yellow

The author's model doesn't actually contain a value to match with, but if we show yellow we're saying that the author did input that, which is confusing.  This happens in Dragoon too.  Here's two possible alternative designs:

* In modes with feedback on selection, disable fields which vary based on the node type until the selected node type is correct.
* Keep the current enable/disable behavior, but make the field always show red until they fix the type (never show yellow if it's not in the author's model.

**Comment by jonwetzel** [comment]
Kurt prefers disabling fields based on type in modes with feedback on selection.

**Comment by dharanisakary** [comment]
I see that it is already in place in topomath, made changes in Dragoon for this.
