### ISSUE TITLE
Change display for incomplete nodes

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#320]
There are two problems with the way we display incompletness on nodes right now:
1. The dotted node borders get smoothed by anti-aliasing at some zoom levels/browser configurations
2. The checkmark is confusing because people associate a checked box with "done".

Current design: dotted border = incomplete, solid border = complete

New design: 

- The body of the nodes now always have solid borders.
- Icons in the top left of the node will be empty for green and yellow nodes, if the node is incomplete (new behavior in bold, unchanged behaviors in normal font):
  - If no description selected yet: grey node with no icon and text "Click here!"
  - Else if node has an incorrect value: icon has red border with "x" (same as now)
  - **Else if user took too many tries on one field (got a yellow), but node is still incomplete: yellow border with no icon in center**
  - Else if user took too many tries on one field (got a yellow), but node is complete: yellow border with minus sign
  - Else if node is complete and all answers input so far are correct on the first try: green border with gold star
  - Else if node is complete and all everything is correct but not on the first try: green border with green check
  - **Else if node is incomplete but all answers input so far are correct: green border with no icon in center**

**Comment by sachingrover211** [comment]
@jonwetzel @dharanisakary as per the discussion on Friday I think this one has been put on hold.
