### ISSUE TITLE
Documentation - Sachin

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#336]

**Comment by sachingrover211** [comment]
@jonwetzel I have written the complete documentation for major parts of topomath. I have also moved the equation-solver.md to topomath-solver as it belongs to that repo. I have added a README for topomath-solver as well. Now I am working on functional level documentation. It has been completed for the math-solver. I am slowly and steadily writing it and will commit it once I am at a logical end.

**Comment by sachingrover211** [comment]
There is still a Small amount of work left for it so I would keep it here.

**Comment by vanlehn** [comment]
Let's just assume its done enough
