### ISSUE TITLE
Author: Schema & Entity fields

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#345]
Update equation editor to have these fields: 
https://www.gomockingbird.com/projects/esbufe3/4gXVnC

- [x] Add Schema and Entity fields like in mockup
- [x] Change description field into a one line text box.
- [x] Populate schema dropdown using values from the schema table, in order of json.  Default value is "\<Select a schema\>" like other dialogs.
- [x] Save values author enters into the model when user clicks done or check equation.
- [x] Hint for entity should say "Enter a list of valid entity names, separated by semicolons"
- [x] The hint icon for schema opens the schema table in a new modal instead of showing a tooltip.
- [x] Hide Add quantity button from Author mode
- [x] If the entity field is exited and has no valid names inside, print a message and color the entity field red.  (Moved to https://github.com/Dragoon-Lab/topomath/issues/360)

**Comment by jonwetzel** [comment]
Resolved by #374
