### ISSUE TITLE
Graph vs Parameter -- can't graph all vs parameters

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#351]
I have a system with 3 variables in one equation (d = r*t). r and t are parameters, d is unknown. In the graph vs parameter tab, I can plot d vs r but not d vs t. Nothing happens when I click the dropdown button to try to switch from r to some other variable. It appears to only work if I type and switch tabs back and forth. When you make the above change, also make sure all the parameters appear in the dropdown.

**Comment by sachingrover211** [comment]
@jonwetzel Good catch, there are a few things wrong there. I am working on this. I am giving this a S, and will make sure all the bugs around it are also solved.
