### ISSUE TITLE
Author mode: Equation validation

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#359]
When the user hits check equation there are two new checks that must be done at the start:

1) The equation must match the schema template unless the schema is "other equation".
2) If the schema is not "other equation", the variable names must all either be existing variables in the model, or new ones from the template (e.g. Dn where the highest variable D in the system so far is Dn-1).

If either of these are not true, turn the equation box red and print an appropriate error message.

Also, update the data structure of available variable numbers.

**Comment by jonwetzel** [comment]
This prevents students from naming the variables inappropriately, like using "R" for a distance or using X, Y, and Z everywhere.

**Comment by vanlehn** [comment]
This is obsolete
