### ISSUE TITLE
Schema Editing and Reconstruction mode step 2: Enter schema and entity names by typing

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#363]
### Matching algorithm
- [ ] Implement a matching algorithm that given a string A and list of strings B and returns either: the string from B which has the lowest minimal-edit (Levenstein) distance **less than 2** to B , otherwise the empty string.  Put this in controller.js.

###  Schema field
Excerpt from design doc:

Clicking on Add Equation brings up the editor form described above.  However, only the schema type-in box is enabled.  All the others are disabled.  Whenever the student edits the value, TopoMath compares it to the names in the schema table.  If none match, it turns the type-in box red with the message “Sorry, <entry> is not in the schema table.  Click the ? button next to the word “Schema:” in order to see the schema table.”  In other words, TopoMath forces authors to enter only legal schemas when it is in Schema editing mode.
If the student enters a string that matches a schema name, then the entity type-in box enables, and the student’s cursor is placed in it. 
- [ ] The user must type the schema name instead of selecting it from a drop down.
- [ ] If the schema entered matches one of the schema names, replace it with that name and mark it as correct.

### Entity field
- [ ] If the schema is not red, merge all entities from the unused author equations which use that schema into one list.  Check to see if the student's entity value matches a value from that list using the above algorithm.  If it does, accept that value as correct.  Otherwise mark incorrect.

**Comment by vanlehn** [comment]
Doesn't work for entities because they are specific to a problem so not easy to guess.  Not much of an improvement memory-wise of schema menu.  Thus, closing.
