### ISSUE TITLE
Handle right click menu for quantity node when that quantity node is part of some equation.

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#386]
Follow up to #349.  User should not be able to delete a variable node if that node is part of an equation.  If the user right clicks on such a node, instead of seeing the delete option they should see this text: "Cannot delete, remove this node from all equations first."

You can disable the menu option and change its label if that's the easiest way to implement this.

Variables not in an equations and equation nodes themselves should still show the standard right click menu with the delete option.

**Comment by vanlehn** [comment]
fixed
