### ISSUE TITLE
Schema dropdown doesn't work twice in the same tab

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#389]
1. Add equation
1. Select a schema
1. Click Done
1. Go back to login.html
1. Open a new problem in author mode
1. Click add equation
1. Click select a schema

The schema list is now blank.  Workaround: Open a new problem from login.html using a new tab and it  works fine--must be a caching issue which happens when the user re-uses the tab.

**Comment by jonwetzel** [comment]
I can't reproduce this bug now.  Demoting priority until I can reproduce it again.

**Comment by riteshsamala** [comment]
This was fixed in one of the previous PRs.
