### ISSUE TITLE
Author mode: given-to-student feature for reconstruction problems

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#393]
Currently the given-to-student feature in author mode is disabled.  We need to bring it back.  It may need some additional tweaks now that we've changed the node editor.

Just like the main editor, it should load the schema and use that to generate the variable fields.  Then the equation should be used to fill in the variable names, because the names are not saved separately in the model.

Note that unlike older versions, we currently don't allow the user to save an incomplete version of the equation.  They must have a valid equation or the node editor won't close.  This can apply to the given to student model as well.

**Comment by jonwetzel** [comment]
If it's easier, add 2 flags, one to give all parameters and another to give all DRTs.

**Comment by vanlehn** [comment]
using DRT and parameter node flags now
