### ISSUE TITLE
Convert DRT schema to Rate (and other changes)

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#413]
Change the name in the menu & schema table to "Rate"
Change the names of the slots to: Rate, Distance or Stuff, Time
Change the equation to be Rate = Stuff / Time.
change the description in the schema table to be:
If a vehicle travels distance D during time T, then its rate R is D/T.  If something consumes or produces S stuff during time T, then its rate R is S/T.

**Comment by jonwetzel** [comment]
Resolved: https://github.com/Dragoon-Lab/topomath/pull/417
