### ISSUE TITLE
Solver crashes?

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#436]
Try Graph or Toable button on TCA>Test>Work Halves consecutively.  Nothing happens.

**Comment by vanlehn** [comment]
user = TCA
folder = Text
model = work halves consecutively
mode = author

When you click on table or graph, nothing appears on the screen. The browser's developer window shoes an uncaught error. This problem is done on paper, so fixing the bug is not urgent.

**Comment by vanlehn** [comment]
I reduced the model above to a quadratic equation and entered it as the model TCA>Text>RJose.  It still throws an error.

**Comment by jonwetzel** [comment]
I'll report this to Sachin...

**Comment by jonwetzel** [comment]
It looks like the solver is returning a fine solution, but the graph window is failing in its constructor.

**Comment by jonwetzel** [comment]
Will be resolved by #458.
