### ISSUE TITLE
User is forced to choose a unit when there is no unit

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#447]
When the author makes a quantity without units, it should work like in Dragoon--I think there the student does not have to enter the units field and it just says "No Units".  Double check how Dragoon works and then make TopoMath work the same.

**Comment by vanlehn** [comment]
If the author leaves the units field blank, then TopoMath hides the units field from the student.  Otherwise, whatever the author typed has to be selected by the studnet, even if it is "no units".
