### ISSUE TITLE
Update the LMS code to make it compatible to the new DB structure we decided to make a while ago. 

### ISSUE THREAD

**Issue by riteshsamala** [Dragoon-Lab/topomath#466]
This task needs to be done on a new branch. For each table structure updated, we need to also update the queries which interact with that table. Also, it has to be tested with the API side on tutor to make sure all the changes wont affect loading models, assignments etc.

**Comment by jonwetzel** [comment]
Issue moved to [Dragoon-Lab/LMS #130](https://github.com/Dragoon-Lab/LMS/issues/130) via [**ZenHub**](https://www.zenhub.com/)
