### ISSUE TITLE
Alien nodes getting switched in Mixture schema

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#471]
Notice drinking water is an mixture schema
1.	Add equation
2.	Schema menu: Mixture [g(reen)]
3.	Relationship menu: b Drinking water rcomposition [g]
4.	Amount of Ingredient type in: InDrink
5.	Amount of Whole Mixture: type WDrink
6.	Proportion of Ingredient to whole: type PDrink
7.	Close [g]
Notice seatwater is an mixture schema
8.	Add equation
9.	Schema menu: Mixture [g]
10.	Relationship menu: a Seawater composition [g]
11.	Amount of Ingredient type in: InSea
12.	Amount of Whole Mixture: type WSea
13.	Proportion of Ingredient to whole: type PSea
14.	Close [red]
If you reopen this equation node, it has switched the fillers of the second two slots.  Now Amount of Whole Mixture is filled with PSea and is green,na dProportion of Ingredient to Whole is filled with WSea and is red.  It should have them the way it was originally defined and WSea should be red.

**Comment by vanlehn** [comment]
when parameters are entered, the alien node gets a green description.
Notice drinking water is an mixture schema
1.	Add equation
2.	Schema menu: Mixture [g(reen)]
3.	Relationship menu: b Drinking water rcomposition [g]
4.	Amount of Ingredient type in: InDrink
5.	Amount of Whole Mixture: type WDrink
6.	Proportion of Ingredient to whole: type PDrink
7.	Close [g]
Notice seatwater is an mixture schema
8.	Add equation
9.	Schema menu: Mixture [g]
10.	Relationship menu: a Seawater composition [g]
11.	Amount of Ingredient type in: InSea
12.	Amount of Whole Mixture: type WSea
13.	Proportion of Ingredient to whole: type PSea
14.	Close [red].  
The Wsea node has no status label (the rounded square in the upper left corner of the node).  This indicates that it doesn’t match a quantity node in the author’s model.  Its slot should have been filled with a previously defined quantity.  
Fill in parameters
15.	Click on PDrink
16.	Parameter [g, but buggy]
17.	Value: 0.0018 [g]
18.	Units: choose a unit [g but buggy]
19.	Close [g]
20.	Click on PSea
21.	Parameter [g, buggy]
22.	Value: 0.035 [g]
23.	Units: choose a unit [g, buggy]
24.	Close [g]
25.	Click on WSea in order to enter “1000 g”
It has a green description "Max amount of salt in drinking water"

**Comment by riteshsamala** [comment]
The root cause for both the issues above is in the schema table, for the mixture schema, the order of parameters in the schema and slots has been reversed. I updated the equation for mixture schema.

Issue 1: This will not happen automatically since we fixed the schema.
Issue 2: Author model needs to be updated for this to have the right values coming in feedback mode.

**Comment by jonwetzel** [comment]
@riteshsamala  The fix looks good.  

@vanlehn  Which model and folder is this so I can update and test it accordingly?

**Comment by riteshsamala** [comment]
@jonwetzel Desalinization in "chapter 3 quiz extras-tca"
