### ISSUE TITLE
Slacker Detection

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#507]
Discuss offline.

**Comment by riteshsamala** [comment]
- [ ] Giving **same wrong** answer twice
- [ ] Feedback abuse (Dead Ring)
- [ ] When the Dropdowns count is low (check the timing between the two selections)

**Comment by vanlehn** [comment]
•	Star (all steps have attempt count 0)
•	Green (all steps have attempt count 0 or 1)
•	One yellow, rest green -  trying hard, but incompetent
•	At most one green, rest yellow -- slacking
