### ISSUE TITLE
Moving assignment links between classes

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#534]
Links don't work because the models are still in the previous classes section.  

When copying assignment links to another class, the source models must be also be copied, and their links updated.

There's no UI for this now.  We should decide if we want to add that.

**Comment by vanlehn** [comment]
Takes less time to do this manually than to debug the move.  Just remember to do it each time CPI and SOS start.

**Comment by vanlehn** [comment]
see design card
