### ISSUE TITLE
Minimize height of problem text

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#589]
In order to create more room for relationships, make the problem text spread across the whole window.  Thus, if the user makes the window wide, then the text becomes fewer lines high, leaving more room for relationships.   Low priority

**Comment by jonwetzel** [comment]
Issue moved to [Dragoon-Lab/topomathv2 #28](https://github.com/Dragoon-Lab/topomathv2/issues/28) via [**ZenHub**](https://www.zenhub.com/)
