### ISSUE TITLE
Display feedback icons on nodes

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#76]
When feedback is shown on nodes, they have four possible states they can display.  In Dragoon these are:

1. All fields correct on the first try  (green border + green fill)
1. All fields correct, but at least one was not on the first try (green border)
1. At least one field is incorrect (red border)
1. At least one field was filled in by the system because the user took too many tries (yellow border)

In TopoMath we'll use the same states, but we'll add icons to the top right of the node.  The preliminary ideas were: 

1. All fields correct on the first try  (green box with gold star inside)
1. All fields correct, but at least one was not on the first try (green box with green checkmark inside)
1. At least one field is incorrect (red box with red x inside)
1. At least one field was filled in by the system because the user took too many tries (yellow box with yellow checkmark inside)

![20170313_144844](https://cloud.githubusercontent.com/assets/8634238/23920207/f9cd4f1e-08b6-11e7-9eda-1e1389a62eac.jpg)
 
This specific set icons may or may not be possible with our current framework.  The goal of this task is to explore the options for implementing the icons.  Explore at least these four options:

1. Dojo -- see if there is an icon library
1. Bootstrap -- we've considered adding this for some time, maybe now would be worth it.  Find out how much work it will be.
1. One or more other icon libraries which might work with our existing framework.
1. Instead of using an icon library, using our own created images.

For each option, figure out if it's feasible to implement, estimate a t-shirt size for implementation, and then rank the options from simplest to most complicated to implement.

**Comment by jonwetzel** [comment]
Dojo has an icon library.  Next step is to choose icons from there.

**Comment by sachingrover211** [comment]
@dharanisakary had showed this to Kurt in the last meeting.
